apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  LIVEKIT_API_KEY: {{ .Values.env.LIVEKIT_API_KEY | quote }}
  LIVEKIT_API_SECRET: {{ .Values.env.LIVEKIT_API_SECRET | quote }}
