spring:
  application:
    name: voice-service

livekit:
  api-key: ${LIVEKIT_API_KEY}
  api-secret: ${LIVEKIT_API_SECRET}
  host: ${LIVEKIT_HOST}
  url: ${LIVEKIT_URL}

server:
  port: ${DEV_ENV_SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  metrics:
    enable:
      all: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true