spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${DEV_ENV_HOST}:5432/${DEV_ENV_DB_NAME}
    username: ${DEV_ENV_DB_USER}
    password: ${DEV_ENV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
#  liquibase:
#    enabled: false
  cloud:
    openfeign:
      client:
        config:
          notification-service:
            url: http://${DEV_ENV_NOTIFICATION_HOST}:${DEV_ENV_NOTIFICATION_PORT}

  kafka:
    topic:
      verify-user-email: verify-user-email
    bootstrap-servers: ${DEV_ENV_HOST_KAFKA}:${DEV_ENV_PORT_KAFKA}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        retries: 5
        retry.backoff.ms: 1000
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

feign:
  notification-service-api:
    base-path: /api/notification-service/mail
    endpoints:
      send-email: /send-mail

notification-service:
  transport-type: ${DEV_ENV_NOTIFICATION_TRANSPORT_TYPE}

app:
  s3:
    bucket: ${DEV_ENV_S3_BUCKET}
    endpoint: ${DEV_ENV_S3_ENDPOINT}
    region: ${DEV_ENV_S3_REGION}
    access-key: ${DEV_ENV_S3_ACCESS_KEY}
    secret-key: ${DEV_ENV_S3_SECRET_KEY}

server:
  port: ${DEV_ENV_SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  metrics:
    enable:
      all: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true