spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${DEV_ENV_HOST}:5432/${DEV_ENV_DB_NAME}
    username: ${DEV_ENV_DB_USER}
    password: ${DEV_ENV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
#  liquibase:
#    enabled: false
  cloud:
    openfeign:
      client:
        config:
          notification-service:
            url: http://${DEV_ENV_HOST}:8083

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

feign:
  notification-service-api:
    base-path: /api/notification-service/mail
    endpoints:
      send-email: /send-mail

notification-service:
  transport-type: HTTP