apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  MAIL_SENDER_PASSWORD: {{ .Values.env.MAIL_SENDER_PASSWORD | quote }}
  MAIL_SENDER_USERNAME: {{ .Values.env.MAIL_SENDER_USERNAME | quote }}
