name: server-service

replicaCount: 1

image:
  repository: whomustnotbenamed/hasslspace
  tag: server-service-1.2.2-arm64
  pullPolicy: IfNotPresent

service:
  port: 8082

env:
  DB_HOST: host.minikube.internal
  DB_PORT: "5432"
  DB_NAME: ""
  DB_USER: ""
  DB_PASSWORD: ""

  S3_BUCKET: s3-hasslspace
  S3_ENDPOINT: https://storage.yandexcloud.net
  S3_REGION: ru-central1
  S3_ACCESS_KEY: ""
  S3_SECRET_KEY: ""

  INVITE_URL: ""
