spring:
  application:
    name: chat-service
  datasource:
    url: jdbc:postgresql://${DEV_ENV_HOST}:5432/${DEV_ENV_DB_NAME}
    username: ${DEV_ENV_DB_USER}
    password: ${DEV_ENV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
#  liquibase:
#    enabled: true
  #logging:
  #  level:
  #    org.springframework.jdbc.core: DEBUG
  cloud:
    openfeign:
      client:
        config:
          centrifugo-service:
            url: http://${DEV_ENV_CENTRIFUGO_HOST}:${DEV_ENV_CENTRIFUGO_PORT}
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

feign:
  centrifugo-api:
    endpoints:
      api: /api
    method: publish
    api_key: ${DEV_ENV_CENTRIFUGO_API_KEY}

server:
    port: ${DEV_ENV_SERVER_PORT}

jwt:
    secret: ${DEV_ENV_JWT_SECRET}
    expiration: ${DEV_ENV_JWT_EXPIRATION}

app:
  s3:
    bucket: ${DEV_ENV_S3_BUCKET}
    endpoint: ${DEV_ENV_S3_ENDPOINT}
    region: ${DEV_ENV_S3_REGION}
    access-key: ${DEV_ENV_S3_ACCESS_KEY}
    secret-key: ${DEV_ENV_S3_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  metrics:
    enable:
      all: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true